# Generated by Django 6.0 on 2025-12-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('НПТО', 'НПТО'), ('ПТО', 'ПТО'), ('Директор', 'Директор'), ('Снабжение', 'Снабжение'), ('Админ', 'Админ'), ('Гость', 'Гость')], default='Гость', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
