# Generated by Django 6.0 on 2025-12-30 07:46

from django.db import migrations, models
import django.db.models.deletion


def create_default_building_site(apps, schema_editor):
    """Создает строительный участок по умолчанию, если его нет"""
    BuildingSite = apps.get_model('building_sites', 'BuildingSite')
    if not BuildingSite.objects.exists():
        BuildingSite.objects.create(
            name='Не указан',
            description='Строительный участок по умолчанию'
        )


def assign_default_building_site(apps, schema_editor):
    """Назначает строительный участок по умолчанию всем проектам без участка"""
    BuildingSite = apps.get_model('building_sites', 'BuildingSite')
    Project = apps.get_model('projects', 'Project')
    default_site = BuildingSite.objects.first()
    if default_site:
        Project.objects.filter(construction_site__isnull=True).update(
            construction_site=default_site
        )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_construction_site'),
        ('building_sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_building_site, migrations.RunPython.noop),
        migrations.RunPython(assign_default_building_site, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='construction_site',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='projects',
                to='building_sites.buildingsite',
                verbose_name='Строительный участок'
            ),
        ),
    ]
