# Generated by Django 6.0 on 2025-12-30 11:43

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_notefile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('for_whom', models.CharField(max_length=200, verbose_name='Для')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Потребность',
                'verbose_name_plural': 'Потребности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.models.requirement_file_upload_path, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_size', models.IntegerField(verbose_name='Размер файла (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.requirement', verbose_name='Потребность')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_requirement_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл потребности',
                'verbose_name_plural': 'Файлы потребностей',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
