# Generated by Django 6.0 on 2025-12-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_requirement_requirementfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыта'),
        ),
    ]
