# Generated by Django 6.0 on 2025-12-30 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_sites', to=settings.AUTH_USER_MODEL, verbose_name='Начальник участка')),
            ],
            options={
                'verbose_name': 'Строительный участок',
                'verbose_name_plural': 'Строительные участки',
                'ordering': ['name'],
            },
        ),
    ]
